services:
  - type: web
    name: liver-cirrhosis-predictor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python flask/app.py
    envVars:
      - key: FLASK_ENV
        value: production
